require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/k_tag_add_relation_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # KTagAddRelationRequest. As you add validations to KTagAddRelationRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      KTagAddRelationRequest.create! valid_attributes
      get k_tag_add_relation_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      k_tag_add_relation_request = KTagAddRelationRequest.create! valid_attributes
      get k_tag_add_relation_request_url(k_tag_add_relation_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_k_tag_add_relation_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      k_tag_add_relation_request = KTagAddRelationRequest.create! valid_attributes
      get edit_k_tag_add_relation_request_url(k_tag_add_relation_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new KTagAddRelationRequest" do
        expect {
          post k_tag_add_relation_requests_url, params: { k_tag_add_relation_request: valid_attributes }
        }.to change(KTagAddRelationRequest, :count).by(1)
      end

      it "redirects to the created k_tag_add_relation_request" do
        post k_tag_add_relation_requests_url, params: { k_tag_add_relation_request: valid_attributes }
        expect(response).to redirect_to(k_tag_add_relation_request_url(KTagAddRelationRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new KTagAddRelationRequest" do
        expect {
          post k_tag_add_relation_requests_url, params: { k_tag_add_relation_request: invalid_attributes }
        }.to change(KTagAddRelationRequest, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post k_tag_add_relation_requests_url, params: { k_tag_add_relation_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested k_tag_add_relation_request" do
        k_tag_add_relation_request = KTagAddRelationRequest.create! valid_attributes
        patch k_tag_add_relation_request_url(k_tag_add_relation_request), params: { k_tag_add_relation_request: new_attributes }
        k_tag_add_relation_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the k_tag_add_relation_request" do
        k_tag_add_relation_request = KTagAddRelationRequest.create! valid_attributes
        patch k_tag_add_relation_request_url(k_tag_add_relation_request), params: { k_tag_add_relation_request: new_attributes }
        k_tag_add_relation_request.reload
        expect(response).to redirect_to(k_tag_add_relation_request_url(k_tag_add_relation_request))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        k_tag_add_relation_request = KTagAddRelationRequest.create! valid_attributes
        patch k_tag_add_relation_request_url(k_tag_add_relation_request), params: { k_tag_add_relation_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested k_tag_add_relation_request" do
      k_tag_add_relation_request = KTagAddRelationRequest.create! valid_attributes
      expect {
        delete k_tag_add_relation_request_url(k_tag_add_relation_request)
      }.to change(KTagAddRelationRequest, :count).by(-1)
    end

    it "redirects to the k_tag_add_relation_requests list" do
      k_tag_add_relation_request = KTagAddRelationRequest.create! valid_attributes
      delete k_tag_add_relation_request_url(k_tag_add_relation_request)
      expect(response).to redirect_to(k_tag_add_relation_requests_url)
    end
  end
end
